# Generated by Django 4.0.3 on 2022-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('lugar_recidencia', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('identificacion', models.IntegerField()),
                ('tipo_identificacion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.CharField(max_length=20)),
            ],
        ),
    ]
